// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetadata } from './fileMetadata'
import type { ItemsArtLayers } from './itemsArtLayers'
import type { ItemsArtListTap } from './itemsArtlistTap'
import type { ItemsArtListTog } from './itemsArtlistTog'
import type { ItemsFadList } from './itemsFadlist'
import type { ItemsFullRanges } from './itemsFullRanges'

export type FileItem = {
  id: string
  locked: boolean
  name: string
  notes: string
  channel: number
  base_delay: number
  avg_delay: number
  vep_out: string
  vep_instance: string
  smp_number: string
  smp_out: string
  color: string
}

export type FileItemRequest = {
  id: string
  locked?: boolean
  name?: string
  notes?: string
  channel?: number
  base_delay?: number
  avg_delay?: number
  vep_out?: string
  vep_instance?: string
  smp_number?: string
  smp_out?: string
  color?: string
}

export type FullTrackCounts = {
  art_list_tog: number
  art_list_tap: number
  art_layers: number
  fad_list: number
  full_ranges: number
}

export type FullTrackForExport = {
  full_ranges: Array<ItemsFullRanges>
  fad_list: Array<ItemsFadList>
  art_list_tog: Array<ItemsArtListTog>
  art_list_tap: Array<ItemsArtListTap>
  art_layers: Array<ItemsArtLayers>
  id: string
  locked: boolean
  name: string
  notes: string
  channel: number
  base_delay: number
  avg_delay: number
  vep_out: string
  vep_instance: string
  smp_number: string
  smp_out: string
  color: string
}

export type FullTrackListForExport = {
  file_meta_data: FileMetadata
  items: Array<FullTrackForExport>
}

export type FullTrackWithCounts = {
  _count: FullTrackCounts
  id: string
  locked: boolean
  name: string
  notes: string
  channel: number
  base_delay: number
  avg_delay: number
  vep_out: string
  vep_instance: string
  smp_number: string
  smp_out: string
  color: string
}
