// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemsFadList = {
  id: string
  name: string
  code_type: string
  code: number
  default: number
  change_type: string
  fileitems_item_id: string
}

export type ItemsFadListRequest = {
  id: string
  name?: string
  code_type?: string
  code?: number
  default?: number
  change_type?: string
  fileitems_item_id?: string
}
