// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemsArtLayers = {
  id: string
  name: string
  code_type: string
  code: number
  on: number
  off: number
  default: string
  change_type: string
  fileitems_item_id: string
}

export type ItemsArtLayersRequest = {
  id: string
  name?: string
  code_type?: string
  code?: number
  on?: number
  off?: number
  default?: string
  change_type?: string
  fileitems_item_id?: string
}
