// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemsFullRanges = {
  id: string
  name: string
  low: string
  high: string
  white_keys_only: boolean
  fileitems_item_id: string
}

export type ItemsFullRangesRequest = {
  id: string
  name?: string
  low?: string
  high?: string
  white_keys_only?: boolean
  fileitems_item_id?: string
}
