// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemsArtListTog = {
  id: string
  name: string
  toggle: boolean
  code_type: string
  code: number
  on: number
  off: number
  default: string
  delay: number
  change_type: string
  ranges: string
  art_layers: string
  fileitems_item_id: string
}

export type ItemsArtListTogRequest = {
  id: string
  name?: string
  toggle?: boolean
  code_type?: string
  code?: number
  on?: number
  off?: number
  default?: string
  delay?: number
  change_type?: string
  ranges?: string
  art_layers?: string
  fileitems_item_id?: string
}
