// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = {
  vep_out_settings: number
  smp_out_settings: number
  default_range_count: number
  default_art_tog_count: number
  default_art_tap_count: number
  default_fad_tog_count: number
  track_add_count: number
  sub_item_add_count: number
  selected_item_id: string
  selected_sub_item_id: string
  previous_item_id: string | null
  next_item_id: string
}
